version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pg-docker
    restart: always
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: demoDB
    ports:
      - "5430:5432"